on: [push, pull_request]
name: Continuous Integration

jobs:
  build-45:
    name: Build Rust 1.45.2
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.45.2
          profile: minimal
          target: wasm32-wasi
          override: true
      - run: |
          sudo apt install libtinfo5
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-11/wasi-sdk_11.0_amd64_ubuntu20.04.deb
          sudo dpkg -i wasi-sdk_11.0_amd64_ubuntu20.04.deb
          rm wasi-sdk_11.0_amd64_ubuntu20.04.deb
        shell: bash
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target wasm32-wasi
        env:
          CC_wasm32_wasi: /opt/wasi-sdk/bin/clang
          CARGO_TARGET_WASM32_WASI_LINKER: /opt/wasi-sdk/bin/clang
  build-46:
    name: Build Rust 1.46.0
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.46.0
          profile: minimal
          target: wasm32-wasi
          override: true
      - run: |
          sudo apt install libtinfo5
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-11/wasi-sdk_11.0_amd64_ubuntu20.04.deb
          sudo dpkg -i wasi-sdk_11.0_amd64_ubuntu20.04.deb
          rm wasi-sdk_11.0_amd64_ubuntu20.04.deb
        shell: bash
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target wasm32-wasi
        env:
          CC_wasm32_wasi: /opt/wasi-sdk/bin/clang
          CARGO_TARGET_WASM32_WASI_LINKER: /opt/wasi-sdk/bin/clang
  build-nightly:
    name: Build Rust nightly
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          profile: minimal
          target: wasm32-wasi
          override: true
      - run: |
          sudo apt install libtinfo5
          wget https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-11/wasi-sdk_11.0_amd64_ubuntu20.04.deb
          sudo dpkg -i wasi-sdk_11.0_amd64_ubuntu20.04.deb
          rm wasi-sdk_11.0_amd64_ubuntu20.04.deb
        shell: bash
      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target wasm32-wasi
        env:
          CC_wasm32_wasi: /opt/wasi-sdk/bin/clang
          CARGO_TARGET_WASM32_WASI_LINKER: /opt/wasi-sdk/bin/clang
